### ISSUE TITLE
Refactor `main` method into a Thread

### ISSUE THREAD

**Issue by NeonDaniel** [NeonGeckoCom/neon_speech#53]
Refactor service into a thread like https://github.com/NeonGeckoCom/NeonCore/blob/master/neon_core/skills/__main__.py

**Comment by NeonJarbas** [comment]
hold on this one for ovos-core 0.0.2, it has been refactored there and it should be subclassed

https://github.com/OpenVoiceOS/ovos-core/blob/dev/mycroft/client/speech/service.py

**Comment by JarbasAl** [comment]
will be closed by #44
